source 'https://rubygems.org'

puppetversion = ENV.key?('PUPPET_VERSION') ? "#{ENV['PUPPET_VERSION']}" : ['>= 4.2.1']
gem 'puppet', puppetversion
gem 'puppetlabs_spec_helper'
gem 'beaker-rspec'
gem 'serverspec'